// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXy98Wnob-2L5XfAX2N0khvFBJGOwXTYM',
    appId: '1:830672702109:web:d3ae21f8dfdc1105ab6274',
    messagingSenderId: '830672702109',
    projectId: 'food-delivery-app-49b21',
    authDomain: 'food-delivery-app-49b21.firebaseapp.com',
    storageBucket: 'food-delivery-app-49b21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrJnCPmNhFwVBcg4YPCI2vVaZXbh4MPrU',
    appId: '1:830672702109:android:0d7f38cb5feabc4dab6274',
    messagingSenderId: '830672702109',
    projectId: 'food-delivery-app-49b21',
    storageBucket: 'food-delivery-app-49b21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuNodadMlVRzQTysw0VQbg6NCLUNAiqUI',
    appId: '1:830672702109:ios:24ae98d4af773dc5ab6274',
    messagingSenderId: '830672702109',
    projectId: 'food-delivery-app-49b21',
    storageBucket: 'food-delivery-app-49b21.appspot.com',
    iosClientId: '830672702109-ao4fhial9rrjpqv9b48upsokk72vp3bt.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
